
import java.beans.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.PreparedStatement;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Saba Fatima
 */
public class Supplier extends javax.swing.JFrame {

    /**
     * Creates new form Supplier
     */
    
    public Supplier()   {
        initComponents();
    }
    
    String driver = "oracle.jdbc.OracleDriver";
    String url = "jdbc:oracle:thin:@localhost:1521:ORCL";
    String user = "system";
    String password = "OracleUser";
    
    ResultSet rs;
    PreparedStatement pst;
    Connection con;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Supplier_Num_label = new javax.swing.JLabel();
        Supplier_name_label = new javax.swing.JLabel();
        Supplier_Add_label = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Supplier_status_label = new javax.swing.JLabel();
        Supplier_Number_Field = new javax.swing.JTextField();
        Supplier_Name_Field = new javax.swing.JTextField();
        Supplier_Add_Field = new javax.swing.JTextField();
        Supplier_City_Field = new javax.swing.JTextField();
        Supplier_Status_Field = new javax.swing.JTextField();
        Supplier_city_label = new javax.swing.JLabel();
        Insert_btn = new javax.swing.JButton();
        Update_btn = new javax.swing.JButton();
        next_btn = new javax.swing.JButton();
        Delete_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Supplier_Table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        readBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Supplier_Num_label.setText(" Number");

        Supplier_name_label.setText(" Name");

        Supplier_Add_label.setText(" Address");

        Supplier_status_label.setText("Status");

        Supplier_Add_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Supplier_Add_FieldActionPerformed(evt);
            }
        });

        Supplier_Status_Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Supplier_Status_FieldActionPerformed(evt);
            }
        });

        Supplier_city_label.setText("City");

        Insert_btn.setText("Insert");
        Insert_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Insert_btnActionPerformed(evt);
            }
        });

        Update_btn.setText("Update");
        Update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Update_btnActionPerformed(evt);
            }
        });

        next_btn.setText("Next");
        next_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next_btnActionPerformed(evt);
            }
        });

        Delete_btn.setText("Delete");
        Delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete_btnActionPerformed(evt);
            }
        });

        Supplier_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                " Number", "Name", " Address", " City", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Supplier_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Supplier_TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Supplier_Table);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("SUPPLIERS");

        readBtn.setText("Read");
        readBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Supplier_Add_label)
                            .addComponent(Supplier_name_label)
                            .addComponent(Supplier_city_label)
                            .addComponent(Supplier_status_label)
                            .addComponent(Supplier_Num_label))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Supplier_City_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Supplier_Add_Field)
                                .addComponent(Supplier_Name_Field)
                                .addComponent(Supplier_Status_Field, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Supplier_Number_Field, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Insert_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Update_btn, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(readBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Delete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(next_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Supplier_Number_Field, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Supplier_Num_label))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Supplier_Name_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Supplier_name_label))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Supplier_Add_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Supplier_Add_label))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Supplier_City_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Supplier_city_label))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Supplier_Status_Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Supplier_status_label))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Insert_btn)
                            .addComponent(readBtn))
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(next_btn)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Update_btn)
                        .addComponent(Delete_btn)))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Supplier_Add_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Supplier_Add_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Supplier_Add_FieldActionPerformed

    private void Supplier_Status_FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Supplier_Status_FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Supplier_Status_FieldActionPerformed

    public void tableupdate() throws SQLException {
        
        int c;
        try {
            Class.forName(driver);
             con = DriverManager.getConnection(url, user, password);
             
             pst = con.prepareStatement("select * from SUPPLIER");
            ResultSet rs = pst.executeQuery();
            
            ResultSetMetaData rsd = rs.getMetaData();
            c = rsd.getColumnCount();
            DefaultTableModel dft = (DefaultTableModel)Supplier_Table.getModel();
            dft.setRowCount(0);
            
            while(rs.next()){
                
                Vector v2 = new Vector();
                for(int i=1;i<c;i++){
                    
                    v2.add(rs.getString("SUPNR"));
                    v2.add(rs.getString("SUPNAME"));
                    v2.add(rs.getString("SUPADDRESS"));
                    v2.add(rs.getString("SUPCITY"));
                    v2.add(rs.getString("SUPSTATUS"));
                    
                }
                dft.addRow(v2);
            }
             
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Supplier.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    private void Insert_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Insert_btnActionPerformed
        
        String name, address, city, status;
        
        int id = Integer.valueOf(Supplier_Number_Field.getText());
        name = Supplier_Name_Field.getText();
        address = Supplier_Add_Field.getText();
        city = Supplier_City_Field.getText();
        status = Supplier_Status_Field.getText();
        
        try {
            // TODO add your handling code here:
            Class.forName(driver);
            con = DriverManager.getConnection(url, user, password);
            pst = con.prepareStatement("insert into SUPPLIER (SUPNR,SUPNAME,SUPADDRESS,SUPCITY,SUPSTATUS)values(?,?,?,?,?)");
            pst.setInt(1, id);
            pst.setString(2, name);
            pst.setString(3, address);
            pst.setString(4, city);
            pst.setString(5, status);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"RECORD ADDED!");
            
            Supplier_Number_Field.setText("");
            Supplier_Name_Field.setText("");
            Supplier_Add_Field.setText("");
            Supplier_City_Field.setText("");
            Supplier_Status_Field.setText("");
            Supplier_Number_Field.requestFocus();
            tableupdate();
        } catch (Exception ex) {
            Logger.getLogger(Supplier.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_Insert_btnActionPerformed

    private void Update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Update_btnActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel)Supplier_Table.getModel();
        int selectedIndex = Supplier_Table.getSelectedRow();
        
        int SUPNR = Integer.parseInt(model.getValueAt(selectedIndex, 0).toString());
        int num;
        String name, address, city, status;
        
        
        name = Supplier_Name_Field.getText();
        address = Supplier_Add_Field.getText();
        city = Supplier_City_Field.getText();
        status = Supplier_Status_Field.getText();
        try {
            
            Class.forName(driver);
            con = DriverManager.getConnection(url, user, password);
            
            pst = con.prepareStatement("update SUPPLIER set SUPNAME=?, SUPADDRESS=?,SUPCITY=?,SUPSTATUS=? where SUPNR = ? ");
            pst.setString(1, name);
            pst.setString(2, address);
            pst.setString(3, city);
            pst.setString(4, status);
            pst.setInt(5, SUPNR);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"RECORD UPDATED!");
            
            Supplier_Number_Field.setText("");
            Supplier_Name_Field.setText("");
            Supplier_Add_Field.setText("");
            Supplier_City_Field.setText("");
            Supplier_Status_Field.setText("");
            Supplier_Number_Field.requestFocus();
            
            tableupdate();
            
            
        } catch (ClassNotFoundException | SQLException ex) {
            
            Logger.getLogger(Supplier.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex);
            
        }
    }//GEN-LAST:event_Update_btnActionPerformed

    private void Supplier_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Supplier_TableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) Supplier_Table.getModel();
        int selectedIndex = Supplier_Table.getSelectedRow();
        
        Supplier_Number_Field.setText(model.getValueAt(selectedIndex,0).toString());
        Supplier_Name_Field.setText(model.getValueAt(selectedIndex,1).toString());
         Supplier_Add_Field.setText(model.getValueAt(selectedIndex,2).toString());
        Supplier_City_Field.setText(model.getValueAt(selectedIndex,3).toString());
        Supplier_Status_Field.setText(model.getValueAt(selectedIndex,4).toString());
    }//GEN-LAST:event_Supplier_TableMouseClicked

    private void Delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete_btnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)Supplier_Table.getModel();
        int selectedIndex = Supplier_Table.getSelectedRow();
        
        int id = Integer.parseInt(model.getValueAt(selectedIndex, 0).toString());
        
        int dialogresult = JOptionPane.showConfirmDialog(null,"Do you want to delete the record","WARNING!",JOptionPane.YES_NO_OPTION);
        
        if (dialogresult ==JOptionPane.YES_OPTION){
            
            try {
                
                Class.forName(driver);
                 con= DriverManager.getConnection(url, user, password);
            
            pst = con.prepareStatement("delete from SUPPLIER where SUPNR = ? ");
            
            pst.setInt(1, id);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(this,"RECORD DELETED!");
            tableupdate();
            Supplier_Number_Field.setText("");
            Supplier_Name_Field.setText("");
            Supplier_Add_Field.setText("");
            Supplier_City_Field.setText("");
            Supplier_Status_Field.setText("");
            Supplier_Number_Field.requestFocus();
            
            } 
            
            catch (ClassNotFoundException | SQLException ex) {
                
                Logger.getLogger(Supplier.class.getName()).log(Level.SEVERE, null, ex);
            }
           
    }//GEN-LAST:event_Delete_btnActionPerformed

    private void next_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next_btnActionPerformed
        // TODO add your handling code here:
        Product product = new Product();
        product.setVisible(true);
        dispose();
    }//GEN-LAST:event_next_btnActionPerformed

    private void readBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readBtnActionPerformed
        try {
            // TODO add your handling code here:
            tableupdate();
        } catch (SQLException ex) {
            Logger.getLogger(Supplier.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_readBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Supplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete_btn;
    private javax.swing.JButton Insert_btn;
    private javax.swing.JTextField Supplier_Add_Field;
    private javax.swing.JLabel Supplier_Add_label;
    private javax.swing.JTextField Supplier_City_Field;
    private javax.swing.JTextField Supplier_Name_Field;
    private javax.swing.JLabel Supplier_Num_label;
    private javax.swing.JTextField Supplier_Number_Field;
    private javax.swing.JTextField Supplier_Status_Field;
    private javax.swing.JTable Supplier_Table;
    private javax.swing.JLabel Supplier_city_label;
    private javax.swing.JLabel Supplier_name_label;
    private javax.swing.JLabel Supplier_status_label;
    private javax.swing.JButton Update_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton next_btn;
    private javax.swing.JButton readBtn;
    // End of variables declaration//GEN-END:variables
}
